version: "3.9"
services:
  backend:
    image: mcr.microsoft.com/dotnet/sdk:latest
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres
    networks:
      - default
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/sh -c "dotnet watch run --non-interactive"
  
  frontend:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "80:80"
  
  postgres:
    container_name: postgres_container
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stocknet_api
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - default

networks:
  default:
      